### ISSUE TITLE
Why the 8.9.0 requirement?

### ISSUE THREAD

**Issue by jack-guy** [motss/lit-ntml#23]
This package looks neat - I'd like to try it out! Is there a reason you only support 8.9.0 and above? Wouldn't any 8.* release do the trick?

**Comment by motss** [comment]
It should theoretically work for any Node version below `8.9` but no guarantee on that.

There are a couple of reasons as to why `8.9`:

1. As of `node@8.9` is the version that leverages the new V8 JavaScript engine that uses TurboFan and Ignition Booster. Check this [blog post](https://v8project.blogspot.sg/2017/05/launching-ignition-and-turbofan.html) to learn more.
2. Latest LTS is `node@8.9` because of **1.**.
3. `node@8.9` has already out as of writing this package plus I've been writing everything Node with at least `node@8.9`. So yeah, if you care about things like that, should shift over to using the latest LTS.

Hope this helps.

**Comment by jack-guy** [comment]
Fair enough! For those using Yarn, you can use the `--ignore-engines` flag to install this package regardless.
